const load=require('./harness.js');
const api=load('game.js', src => src + `;global.__f={applyStatus,strike,hitHp,healUnit,startTurn,performAction,applyDebuff,addBuff,cutOf,effStr,effSpd,killUnit,shieldTotal,get b(){return battleUI}};`);
const F=global.__f;
const ok=(name, cond, info)=>console.log((cond?'✅':'❌')+' '+name+(info!==undefined?'  '+JSON.stringify(info):''));
function setup(party){
  api.run([], 'q1_01', 1);
  const S=api.STATE; S.owned={};
  party.forEach(id=>S.owned[id]={star:Math.max(4,api.MON_BY_ID[id].rarity),souls:0,level:30,exp:0,wall:30,skillLv:1,ultLv:1,passiveLv:1});
  S.formationKey='f2'; S.slots=api.lineupFromList(party,'f2'); S.clearedStages=api.STAGES.map(s=>s.id);
  api.startBattle('q1_01',{skipIntro:true});
  const B=F.b; B.transitioning=false; B.paused=true;
  B.enemies.forEach(e=>{ e.maxHp=e.hp=99999; e.str=60; e.pdef=0; e.mdef=0; e.alive=true; });
  B.enemies.slice(1).forEach(e=>{ e.alive=false; });
  return B;
}
const U=(B,id)=>B.party.find(u=>u.ref===id);
const hit=(atk,t,pow,type)=>F.strike({actor:atk,act:{atk:type||'phys'},kind:'normal'}, t, {pow});
let B=setup(['m48','m96','m117','m51','m129']);
let knock=U(B,'m48'), kyon=U(B,'m96'), kappa=U(B,'m117'), giant=U(B,'m51'), hino=U(B,'m129'), e=B.enemies[0];
ok('ノッカー: 戦闘開始時に味方全員へ免疫', B.party.every(u=>u.buffs.ward));
F.applyStatus(kyon,'burn',e);
ok('免疫: 状態異常を1回防いで消える', !kyon.statuses.burn && !kyon.buffs.ward);
F.applyStatus(kyon,'burn',e);
ok('免疫が消えたあとはかかる', !!kyon.statuses.burn);
F.applyDebuff(kappa,'strDown',0.2,2,e);
ok('免疫: デバフも防ぐ', !kappa.buffs.strDown && !kappa.buffs.ward);
kappa.sp=50; F.addBuff(kappa,'ward',1,3,knock); api.STATE; // SP drain isn't blocked
F.strike({actor:e,act:{atk:'phys',onHit:[{drain:10}]},kind:'skill'}, kappa, {pow:0.01});
ok('免疫: SP減少は防がない', kappa.sp<=45 && kappa.buffs.ward, kappa.sp);
const c0=F.cutOf(giant,'phys'); F.addBuff(giant,'vuln',0.2,2,e);
ok('被ダメージアップ: 軽減と足し算', Math.abs(F.cutOf(giant,'phys')-(c0-0.2))<1e-9, [c0, F.cutOf(giant,'phys')]);
giant.hp=10; F.addBuff(giant,'healCut',0.5,2,e); const g=F.healUnit(knock,giant,100);
ok('回復阻害: 受ける回復量-50%', g===50, g);
F.performAction(knock,'ult',knock.kit.ult);
ok('大警報: デバフを1つだけ解除し、免疫を付け直す', ((giant.buffs.healCut?1:0)+(giant.buffs.vuln?1:0))===1 && B.party.every(u=>u.buffs.ward));
const hp0=api.MON_BY_ID.m51.hp;
ok('ヒルジャイアント: 最大HP+10%', giant.maxHp>=Math.round(giant.maxHp/1.1*1.1)-1 && giant.maxHp>Math.round(giant.maxHp/1.1), giant.maxHp);
const s0=F.effStr(kyon);
kyon.hp=Math.round(kyon.maxHp*0.45); F.hitHp(kyon,1,e,{});
ok('キョンシー: HP50%を下回ると札が外れる(STR-20%→+40%)', kyon.flags.unsealed && F.effStr(kyon)>s0*1.6, [s0, F.effStr(kyon)]);
kyon.hp=kyon.maxHp;
ok('キョンシー: 回復しても札は外れたまま', kyon.flags.unsealed && F.effSpd(kyon)===kyon.spd+15);
kappa.hp=Math.round(kappa.maxHp*0.55); giant.hp=10;
F.hitHp(kappa,Math.round(kappa.maxHp*0.1),e,{});
ok('河童: HP50%を下回ったら1度だけ味方全員を回復', giant.hp>10 && kappa.flags.dishUsed, giant.hp);
F.applyStatus(e,'burn',hino); const eh=e.hp; const r=hit(hino,e,1,'mag');
ok('ヒノコ: やけどの敵に当たると追加攻撃', eh-e.hp > r.dmg, [r.dmg, eh-e.hp]);
B=setup(['m115','m98','m61','m131','m62']);
let cat=U(B,'m115'), phar=U(B,'m98'), yeti=U(B,'m61'), frog=U(B,'m131'), bear=U(B,'m62'); e=B.enemies[0];
F.hitHp(cat,99999,e,{});
ok('猫又: 1本目の尾でHP30%復活', cat.alive && cat.hp===Math.round(cat.maxHp*0.3));
F.hitHp(cat,99999,e,{});
ok('猫又: 2本目の尾でHP1で耐える', cat.alive && cat.hp===1);
F.hitHp(cat,99999,e,{});
ok('猫又: 3回目は倒れる', !cat.alive);
F.hitHp(phar,99999,e,{});
ok('ファラオ: HP50%で復活', phar.alive && phar.hp===Math.round(phar.maxHp*0.5));
ok('イエティ: 戦闘開始時に挑発', !!yeti.buffs.taunt);
frog.buffs.evade={v:1,turns:9}; let got=false; for(let i=0;i<10;i++){ hit(e,frog,1); if(frog.buffs.spdUp) got=true; }
ok('ポンドフロッグ: 回避するとSPD+10', got);
F.applyStatus(bear,'stun',e);
ok('ツインヘッドベア: 気絶にかからない', !bear.statuses.stun);
F.performAction(bear,'skill',bear.kit.skill2);
ok('二つの咆哮: 会心率アップのバフ', bear.buffs.critUp && bear.buffs.critUp.v===0.2);
